controller_manager:
  ros__parameters:
    update_rate: 100

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    
    wheel_separation: 0.475 
    wheel_radius: 0.0825
    
    odom_frame_id: odom
    base_frame_id: base_footprint

    use_stamped_vel: false

joint_state_broadcaster:
  ros__parameters:
    use_stamped_vel: false